server:
  port: 88

spring:
  application:
    name: security-gateway
  redis:
    database: 10
    port: 6379
    host: 47.96.86.132
  cloud:
    nacos:
      discovery:
        server-addr: 47.96.86.132:8848
    gateway:
      routes:
        - id: api-routes  #任务模块路由
          uri: lb://security-api
          predicates:
            - Path=/api-user/**
          filters:
            - StripPrefix=1
      #            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
      #        - id: auth-route
      #          uri: lb://security-auth
      #          predicates:
      #            - Path=/auth/user/**
      #          filters:
      #            - RewritePath=/auth/(?<segment>/?.*),/$\{segment}
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写

        # Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-head: true
